println("                   _.gjUUUUUUUlkBz.,_                   ");
println("                BUUUUUUUUUUUUUUUUUUUUUU,                ");
println("               jUUP^^VUUUUUUUUUUUUUUUUUUU               ");            
println("               UUU    UUUUUUUUUUUUUUUUUUU               ");
println("               UUUUaeBUUUUUUUUUUUUUUUUUUU               ");
println("               UUUUUUUUUUUUUUUUUUUUUUUUUU               ");
println("                            UUUUUUUUUUUUU                   ______                       __                         ");
println("    ,aBUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU  BBBBBBUe,       |  __  |              __     |  |     ");
println("   BUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU  BBBBBBBBBU,     | |__| | __    __  __|  |__  |  |       _____    __");
println("  BUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU  BBBBBBBBBBU,    |   ___/ \\ \\  / / |__    __| |  \\      /  _  \\  |  |_____");
println(" jUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU  BBBBBBBBBBBp,   |  |      \\ \\/ /     |  |    |   \\__  |  / \\  | |        \\");
println("jUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU'  BBBBBBBBBBBBB   |  |       \\  /      |  |    |      ) |  | |  | |   __   |");
println("UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU^'   ,BBBBBBBBBBBBB   |  |       / /       |  |    |  /\\  | |  \\_/  | |  /  \\  |");
println("UUUUUUUUUUUUUU^'                        .BBBBBBBBBBBBBBB   |__|      / /        |__|    |__| |_|  \\_____/  |__|  |__|");
println("UUUUUUUUUUUUU'   .aBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB  __________/_/________________________________________________");
println("UUUUUUUUUUUUU  ,BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB^");
println("^UUUUUUUUUUUU  BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB^ ");
println(" VUUUUUUUUUUU  BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBY  ");
println("  VUUUUUUUUUU  BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBY   ");
println("   `'^UUUUUUU  BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB^'`    ");
println("               BBBBBBBBBBBBB                            ");
println("               BBBBBBBBBBBBBBBBBBBBBBBBBB               ");
println("               BBBBBBBBBBBBBBBBBBBP''VBBB               ");
println("               BBBBBBBBBBBBBBBBBBB    BBB               ");
println("               BBBBBBBBBBBBBBBBBBBUaeBBBV               ");
println("                `^BBBBBBBBBBBBBBBBBBBBB^                ");
println("                  `''^^VBBBBBBBBBV^^'                   ");
